### ISSUE TITLE
hope that you can provide zip of static html page source

### ISSUE THREAD

**Issue by ZhoucpSAMA** [ShevonKuan/nginx-error-page#1]
because it is not only use in nginx ,but also can use in website as error page, it is  so beautiful

**Comment by ZhoucpSAMA** [comment]
I just want to download it and simply modify it to use as a static page on my website. the readme seems to be a bit cumbersome.

**Comment by ShevonKuan** [comment]
Thank you very much for your interest. You can directly download the gh-pages branch, which contains all the static HTML pages: https://github.com/ShevonKuan/nginx-error-page/archive/refs/heads/gh-pages.zip
